### ISSUE TITLE
Closing popup causes crash in IOS

### ISSUE THREAD

**Issue by Mous625** [LuckyDucko/Mopups#25]
Using the `await MopupService.Instance.PopAsync()` causes the app to crash **specifically on IOS**.  On Android, all works well. You can see the error message and stack trace in the image attached. 

![301517862_606932141043297_6605776098673599441_n](https://user-images.githubusercontent.com/43863284/187172325-f51f9ae7-647b-43fd-b102-ead8fbce04f7.png)

If I wrap the  `await MopupService.Instance.PopAsync()` in a try catch, the exception is swallowed however the app still crashes once the screen is touched. Error message and stack trace attached below: 

![301416691_491425982986049_6614557745973874674_n](https://user-images.githubusercontent.com/43863284/187172915-8acbcf1f-9edf-48ff-98f4-78d1dfce1058.png)

Things to note: 

The `ConfigureMopups()` line is added in MauiProgram.cs. 
For navigation, I am using Shell. 

Steps to reproduce (Screenshot 1): 

1. Open popup using `await MopupService.Instance.PushAsync(<Popup>)`
2. Close popup using `await MopupService.Instance.PopAsync()`
3. App crashes 

Steps to reproduce with try-catch (screenshot 2):

1. Open popup using `await MopupService.Instance.PushAsync(<Popup>)`
2. Close popup using `await MopupService.Instance.PopAsync()` (exception doesn't cause crash)
3. Tap on the app 
4. Exception is thrown in Program.cs

**Comment by Mous625** [comment]
@LuckyDucko tagging you here as I don't think I can assign you.

**Comment by LuckyDucko** [comment]
@Mous625  all good, ill sort this one out asap, downgrading makes it work?

**Comment by Mous625** [comment]
Thank you for your prompt reply.

Just checked, and downgrading to 1.0.1 **makes it work** if closing the popup using MopupService manually. However, the error **does occur if the user attempts to close the popup** by swiping down on it. 

P.S when I say manually I mean using the `await MopupService.Instance.PopAsync()` to a button event handler of my own making.

**Comment by LuckyDucko** [comment]
That makes sense, as its an issue with the HitTest function, ill let you know when its sorted :+1:

**Comment by Mous625** [comment]
So curiosity got the better of me and I decided to have a look and added the Mopups project to my own. The error was happening when trying to cast a ViewCell to a VisualElement. I'm not an expert by any means, so I just added a try-catch to that section to ignore cast exceptions and it worked without issues. Please note I have no idea whether simply ignoring the ViewCell is the right approach but this may help speed up the process for you. Here is the code: 

```
private static void DisposeModelAndChildrenHandlers(VisualElement view)
    {
        foreach (VisualElement child in view.GetVisualTreeDescendants())
        {
			try <-------- added by me
			{
				IViewHandler handler = child.Handler;
				child?.Handler?.DisconnectHandler();
				(handler?.PlatformView as UIView)?.RemoveFromSuperview();
				(handler?.PlatformView as UIView)?.Dispose();
			}
			catch(Exception){} <-------- added by me
        }

        view?.Handler?.DisconnectHandler();
        (view?.Handler?.PlatformView as UIView)?.RemoveFromSuperview();
        (view?.Handler?.PlatformView as UIView)?.Dispose();
    }
```

**Comment by LuckyDucko** [comment]
Still getting round to this, just been having issues with my Macbook, so i can't poke where the issues may be, sorry for the delay!

**Comment by LuckyDucko** [comment]
@Mous625 could you provide a sample project for me to work off?

I just tested it then, and it seems to work quite fine on the default project. Perhaps its because you use shell?

Either way, I have a fix in mind, just wanting to get a test case running so I know

**Comment by LuckyDucko** [comment]
<img width="713" alt="Screen Shot 2022-09-07 at 17 23 17" src="https://user-images.githubusercontent.com/17778102/188815057-2efe2f32-7bc8-45fb-8c13-d16a9252fa47.png">
@Mous625 Does the following change fix the issue?

I dont understand why I settled on VisualElement, as this is much more robust if it works

**Comment by LuckyDucko** [comment]
This should be addressed by v 1.0.3

**Comment by Mous625** [comment]
My apologies I forgot to respond as I got bogged down by a new project. This fixes the issue. Thanks.

**Comment by Emtiaz-Tafsir** [comment]
Hello,
I just stumbled upon a rather unique encounter.
I am currently porting a Xamarin.Forms Application to MAUI. And I'm using Mopups as a replacement of RG.Popup. I'm still getting this error when trying to pop a page with ViewCells. I tried with both 1.1.1 and 1.2.0 nuget packages, but the problem persists.
Then I tried to debug with injecting the master code-base directly into my project and the problem went away.
